 CREATE TABLE marketing_campaign (
ID INT PRIMARY KEY,
Year_Birth INT,
Education VARCHAR(50),
Marital_Status VARCHAR(50),
Income NUMERIC,
Kidhome INT,
Teenhome INT,
Dt_Customer DATE,
Recency INT,
MntWines INT,
MntFruits INT,
MntMeatProducts INT,
MntFishProducts INT,
MntSweetProducts INT,
MntGoldProds INT,
NumDealsPurchases INT,
NumWebPurchases INT,
NumCatalogPurchases INT,
NumStorePurchases INT,
NumWebVisitsMonth INT,
AcceptedCmp3 INT,
AcceptedCmp4 INT,
AcceptedCmp5 INT,
AcceptedCmp1 INT,
AcceptedCmp2 INT,
Complain INT,
Z_CostContact INT,
Z_Revenue INT,
Response INT
);
